const defineModel = (name: string, size: string) => ({
  name,
  fileName: `${name}.bin`,
  isQuantized: name.includes("q5") || name.includes("q8"),
  url: `https://huggingface.co/ggerganov/whisper.cpp/resolve/main/${name}.bin?download=true`,
  size,
});

export const modelData = [
  defineModel("ggml-base", "142 MiB"),
  defineModel("ggml-base-q5_1", "57 MiB"),
  defineModel("ggml-base-q8_0", "78 MiB"),
  defineModel("ggml-base.en", "142 MiB"),
  defineModel("ggml-base.en-q5_1", "57 MiB"),
  defineModel("ggml-base.en-q8_0", "78 MiB"),
  defineModel("ggml-large-v1", "2.9 GiB"),
  defineModel("ggml-large-v2", "2.9 GiB"),
  defineModel("ggml-large-v2-q5_0", "1.1 GiB"),
  defineModel("ggml-large-v2-q8_0", "1.5 GiB"),
  defineModel("ggml-large-v3", "2.9 GiB"),
  defineModel("ggml-large-v3-q5_0", "1.1 GiB"),
  defineModel("ggml-large-v3-turbo", "1.5 GiB"),
  defineModel("ggml-large-v3-turbo-q5_0", "547 MiB"),
  defineModel("ggml-large-v3-turbo-q8_0", "834 MiB"),
  defineModel("ggml-medium", "1.5 GiB"),
  defineModel("ggml-medium-q5_0", "514 MiB"),
  defineModel("ggml-medium-q8_0", "785 MiB"),
  defineModel("ggml-medium.en", "1.5 GiB"),
  defineModel("ggml-medium.en-q5_0", "514 MiB"),
  defineModel("ggml-medium.en-q8_0", "785 MiB"),
  defineModel("ggml-small", "466 MiB"),
  defineModel("ggml-small-q5_1", "181 MiB"),
  defineModel("ggml-small-q8_0", "252 MiB"),
  defineModel("ggml-small.en", "466 MiB"),
  defineModel("ggml-small.en-q5_1", "181 MiB"),
  defineModel("ggml-small.en-q8_0", "252 MiB"),
  defineModel("ggml-small.en-tdrz", "465 MiB"),
  defineModel("ggml-tiny", "75 MiB"),
  defineModel("ggml-tiny-q5_1", "31 MiB"),
  defineModel("ggml-tiny-q8_0", "42 MiB"),
  defineModel("ggml-tiny.en", "75 MiB"),
  defineModel("ggml-tiny.en-q5_1", "31 MiB"),
  defineModel("ggml-tiny.en-q8_0", "42 MiB"),
].reduce(
  (acc, model) => {
    acc[model.name] = model;
    return acc;
  },
  {} as Record<string, ReturnType<typeof defineModel>>,
);
