export enum QueryKeys {
  ChatHistory = "chathistory",
  History = "history",
  Transcript = "transcript",
  AudioFile = "audio",
  Settings = "settings",
  HasModel = "hasmodel",
  Theme = "theme",
  Mcp = "mcp",
  PostProcessing = "postprocessing",
  ScreenSources = "screensources",
  MicrophoneSources = "microphonesources",
  DialogData = "dialogdata",
  RecorderIpcState = "recorderipcstate",
}
