export enum QueryKeys {
  History = "history",
  Transcript = "transcript",
  AudioFile = "audio",
  Settings = "settings",
  HasModel = "hasmodel",
  Theme = "theme",
  PostProcessing = "postprocessing",
  ScreenSources = "screensources",
  MicrophoneSources = "microphonesources",
  DialogData = "dialogdata",
  RecorderIpcState = "recorderipcstate",
  VectorStore = "vectorstore",
  VectorSearch = "vectorsearch",
  HybridSearch = "hybridsearch",
}
